name: Nodejs application deploy on EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  VERSION_TAG: ${{ secrets.VERSION }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        #IMAGE_TAG: ${{ env.VERSION_TAG }}
        IMAGE_NUMBER: ${{github.run_number }}

      run: |
        # Build a docker container and push it to ECR 
        docker build -t github:$IMAGE_TAG  .
        #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . test
        docker tag github:$IMAGE_TAG  566903284890.dkr.ecr.ap-south-2.amazonaws.com/github:$IMAGE_TAG 
        echo "Pushing image to ECR..."
        docker push 566903284890.dkr.ecr.ap-south-2.amazonaws.com/github:$IMAGE_TAG 
        #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=IMAGE_NUMBER::1.0${{github.run_number }}"
        #echo "::set-output name=image::566903284890.dkr.ecr.ap-south-2.amazonaws.com/github:$IMAGE_TAG"
